packages:
  - apps/*
  - packages/*

catalog:
  '@types/node': ^26.1.1
  dotenv: ^17.4.2
  zod: ^4.4.3

overrides:
  '@defied/ui': link:../../../AppData/Local/pnpm/global/5/node_modules/@defied/ui
  cli: link:../../../AppData/Local/pnpm/global/5/node_modules/@defied-prism/cli
