import { scales, themes, type TokenPath } from "./tokens";

export * from "./tokens";
export * from "./color";
export * from "./theme";

export const TOKEN_PREFIX = "prism";

/** "color.primary-fg" -> "--prism-color-primary-fg" */
export function cssVarName(path: TokenPath | string): string {
  return `--${TOKEN_PREFIX}-${path.replace(/\./g, "-")}`;
}

/** "color.primary" -> "var(--prism-color-primary)" */
export function cssVar(path: TokenPath | string): string {
  return `var(${cssVarName(path)})`;
}

/** All valid token paths. */
export const tokenPaths: ReadonlySet<string> = new Set([
  ...Object.keys(themes.light).map((key) => `color.${key}`),
  ...Object.entries(scales).flatMap(([group, values]) =>
    Object.keys(values).map((key) => `${group}.${key}`),
  ),
]);

export function isTokenPath(path: string): path is TokenPath {
  return tokenPaths.has(path);
}

const REF = /\{([a-z0-9-]+\.[a-z0-9-]+)\}/gi;

/**
 * Replaces every `{group.name}` reference in a CSS value with its CSS
 * variable. Unknown references throw: a recipe may only use real tokens.
 */
export function resolveTokenRefs(
  value: string,
  onToken?: (path: TokenPath) => void,
): string {
  return value.replace(REF, (_match, path: string) => {
    if (!isTokenPath(path)) {
      throw new Error(`[prism] Unknown design token "{${path}}".`);
    }
    onToken?.(path);
    return cssVar(path);
  });
}

function declarations(entries: [string, string][], indent = "  "): string {
  return entries.map(([name, value]) => `${indent}${name}: ${value};`).join("\n");
}

function colorDeclarations(theme: keyof typeof themes, indent?: string) {
  return declarations(
    Object.entries(themes[theme]).map(([key, value]) => [
      cssVarName(`color.${key}`),
      value,
    ]),
    indent,
  );
}

/**
 * `tokens.css`: every token as a CSS variable. Dark theme applies via
 * `.dark`, `[data-theme="dark"]`, or the OS preference (unless
 * `[data-theme="light"]` opts out). Motion collapses under reduced motion.
 */
export function buildTokensCss(): string {
  const scaleEntries = Object.entries(scales).flatMap(([group, values]) =>
    Object.entries(values).map(
      ([key, value]) => [cssVarName(`${group}.${key}`), value] as [string, string],
    ),
  );

  return `/* Generated by @defied-prism/tokens. Do not edit. */
:root {
  color-scheme: light;
${declarations(scaleEntries)}
${colorDeclarations("light")}
}

.dark,
[data-theme="dark"] {
  color-scheme: dark;
${colorDeclarations("dark")}
}

@media (prefers-color-scheme: dark) {
  :root:not([data-theme="light"]):not(.light) {
    color-scheme: dark;
${colorDeclarations("dark", "    ")}
  }
}

@keyframes prism-spin {
  to {
    transform: rotate(360deg);
  }
}

@keyframes prism-fade-in {
  from {
    opacity: 0;
  }
}

@keyframes prism-scale-in {
  from {
    opacity: 0;
    transform: scale(0.96);
  }
}

/* Loading placeholders (skeletons) */
@keyframes prism-pulse {
  50% {
    opacity: 0.5;
  }
}

/* Indeterminate progress: a partial bar sweeping across its track */
@keyframes prism-indeterminate {
  from {
    transform: translateX(-100%);
  }
  to {
    transform: translateX(250%);
  }
}

/* Edge-anchored panels (drawers); set --prism-slide-x / --prism-slide-y */
@keyframes prism-slide-in {
  from {
    transform: translate(var(--prism-slide-x, 0), var(--prism-slide-y, 0));
  }
}

@media (prefers-reduced-motion: reduce) {
  :root {
${declarations(
  Object.keys(scales.duration).map((key) => [cssVarName(`duration.${key}`), "0ms"]),
  "    ",
)}
  }
}
`;
}

/** Tailwind v4 namespaces for each token group. */
/** Token group -> Tailwind v4 theme namespace (groups without one have no utility scale). */
export const TAILWIND_NAMESPACE: Record<string, string> = {
  color: "color",
  space: "spacing",
  radius: "radius",
  font: "font",
  text: "text",
  leading: "leading",
  weight: "font-weight",
  shadow: "shadow",
  easing: "ease",
};

/**
 * `tailwind.css`: exposes Prism tokens as Tailwind v4 theme values under a
 * `prism-` namespace: `bg-prism-primary`, `px-prism-4`, `rounded-prism-md`.
 * Namespaced so they never collide with an app's own theme (`bg-primary`
 * stays yours). Import after `tailwindcss` and `tokens.css`.
 */
export function buildTailwindCss(): string {
  const entries: [string, string][] = [];
  for (const key of Object.keys(themes.light)) {
    entries.push([`--color-${TOKEN_PREFIX}-${key}`, cssVar(`color.${key}`)]);
  }
  for (const [group, values] of Object.entries(scales)) {
    const namespace = TAILWIND_NAMESPACE[group];
    if (!namespace) continue;
    for (const key of Object.keys(values)) {
      entries.push([`--${namespace}-${TOKEN_PREFIX}-${key}`, cssVar(`${group}.${key}`)]);
    }
  }
  return `/* Generated by @defied-prism/tokens. Do not edit. */
@theme inline {
${declarations(entries)}
}
`;
}

/** Plain data for other tooling (Figma sync, docs, other adapters). */
export function buildTokensJson() {
  return { prefix: TOKEN_PREFIX, themes, scales };
}
