/**
 * Indexes the docs demos: every `src/components/docs/demos/<component>/<demo>.tsx`
 * must have a Vue twin at `apps/vue-demos/src/docs/<component>/<demo>.vue`
 * (and vice versa), so the two frameworks can't drift apart unnoticed.
 *
 * Writes src/generated/docs-demos.ts (lazy React loaders) and
 * src/generated/docs-sources.json (both sources, shown under each preview).
 */
import { existsSync, mkdirSync, readFileSync, readdirSync, writeFileSync } from "node:fs";
import path from "node:path";

const reactDir = path.resolve(import.meta.dirname, "../src/components/docs/demos");
const vueDir = path.resolve(import.meta.dirname, "../../vue-demos/src/docs");
const out = path.resolve(import.meta.dirname, "../src/generated");

function demoIds(dir: string, ext: string): string[] {
  if (!existsSync(dir)) return [];
  return readdirSync(dir, { withFileTypes: true })
    .filter((entry) => entry.isDirectory())
    .flatMap((entry) =>
      readdirSync(path.join(dir, entry.name))
        .filter((file) => file.endsWith(ext))
        .map((file) => `${entry.name}/${file.slice(0, -ext.length)}`),
    )
    .sort();
}

const react = demoIds(reactDir, ".tsx");
const vue = demoIds(vueDir, ".vue");
const missing = [
  ...react.filter((id) => !vue.includes(id)).map((id) => `${id}: no Vue twin (${id}.vue)`),
  ...vue.filter((id) => !react.includes(id)).map((id) => `${id}: no React twin (${id}.tsx)`),
];
if (missing.length) {
  throw new Error(`Docs demos must exist in both frameworks:\n  ${missing.join("\n  ")}`);
}

const sources = Object.fromEntries(
  react.map((id) => [
    id,
    {
      react: readFileSync(path.join(reactDir, `${id}.tsx`), "utf8"),
      vue: readFileSync(path.join(vueDir, `${id}.vue`), "utf8"),
    },
  ]),
);

mkdirSync(out, { recursive: true });
writeFileSync(path.join(out, "docs-sources.json"), JSON.stringify(sources) + "\n");
writeFileSync(
  path.join(out, "docs-demos.ts"),
  `// Generated by scripts/generate-docs.ts\nimport type { ComponentType } from "react";\n\n` +
    `export const reactDemos: Record<string, () => Promise<{ default: ComponentType }>> = {\n` +
    react.map((id) => `  "${id}": () => import("@/components/docs/demos/${id}"),`).join("\n") +
    `\n};\n`,
);
console.log(`docs: ${react.length} demos, each in React and Vue`);
