// Input component style definition using @defied-prism/style-engine DSL
// This file is evaluated at build time by the prism CLI

import {
  defineStyle,
  property,
  bg,
  text,
  rounded,
  paddingX,
  paddingY,
  border,
  focus,
  disabled,
  data,
  placeholder,
} from "@defied-prism/style-engine";

export default defineStyle({
  base: [
    property("display", "block"),
    property("width", "100%"),
    property("fontFamily", "var(--font-sans, system-ui, sans-serif)"),
    property("border", "1px solid var(--color-border)"),
    property("backgroundColor", "var(--color-bg)"),
    property("color", "var(--color-text)"),
    property("outline", "none"),
    property("transition", "all 150ms ease"),
  ],
  variants: {
    "default-sm": [
      data("size", "sm"),
      data("variant", "default"),
      paddingX("spacing-3"),
      paddingY("spacing-2"),
      property("fontSize", "0.875rem"),
      rounded("md"),
      bg("color-bg"),
      text("color-text"),
      property("borderColor", "var(--color-border)"),
    ],
    "default-md": [
      data("size", "md"),
      data("variant", "default"),
      paddingX("spacing-3"),
      paddingY("spacing-2"),
      property("fontSize", "1rem"),
      rounded("md"),
      bg("color-bg"),
      text("color-text"),
      property("borderColor", "var(--color-border)"),
    ],
    "default-lg": [
      data("size", "lg"),
      data("variant", "default"),
      paddingX("spacing-4"),
      paddingY("spacing-3"),
      property("fontSize", "1.125rem"),
      rounded("md"),
      bg("color-bg"),
      text("color-text"),
      property("borderColor", "var(--color-border)"),
    ],
    "filled-sm": [
      data("size", "sm"),
      data("variant", "filled"),
      paddingX("spacing-3"),
      paddingY("spacing-2"),
      property("fontSize", "0.875rem"),
      rounded("md"),
      bg("color-muted"),
      text("color-text"),
      property("borderColor", "transparent"),
    ],
    "filled-md": [
      data("size", "md"),
      data("variant", "filled"),
      paddingX("spacing-3"),
      paddingY("spacing-2"),
      property("fontSize", "1rem"),
      rounded("md"),
      bg("color-muted"),
      text("color-text"),
      property("borderColor", "transparent"),
    ],
    "filled-lg": [
      data("size", "lg"),
      data("variant", "filled"),
      paddingX("spacing-4"),
      paddingY("spacing-3"),
      property("fontSize", "1.125rem"),
      rounded("md"),
      bg("color-muted"),
      text("color-text"),
      property("borderColor", "transparent"),
    ],
    "outlined-sm": [
      data("size", "sm"),
      data("variant", "outlined"),
      paddingX("spacing-3"),
      paddingY("spacing-2"),
      property("fontSize", "0.875rem"),
      rounded("md"),
      bg("color-bg"),
      text("color-text"),
      property("borderColor", "var(--color-border)"),
    ],
    "outlined-md": [
      data("size", "md"),
      data("variant", "outlined"),
      paddingX("spacing-3"),
      paddingY("spacing-2"),
      property("fontSize", "1rem"),
      rounded("md"),
      bg("color-bg"),
      text("color-text"),
      property("borderColor", "var(--color-border)"),
    ],
    "outlined-lg": [
      data("size", "lg"),
      data("variant", "outlined"),
      paddingX("spacing-4"),
      paddingY("spacing-3"),
      property("fontSize", "1.125rem"),
      rounded("md"),
      bg("color-bg"),
      text("color-text"),
      property("borderColor", "var(--color-border)"),
    ],
  },
});
