// Button component style definition using @defied-prism/style-engine DSL
// This file is evaluated at build time by the prism CLI

import {
  defineStyle,
  property,
  bg,
  text,
  rounded,
  paddingX,
  paddingY,
  gap,
  flex,
  transition,
  hover,
  focus,
  disabled,
  data,
} from "@defied-prism/style-engine";

export default defineStyle({
  base: [
    flex(),
    property("display", "inline-flex"),
    property("alignItems", "center"),
    property("justifyContent", "center"),
    property("fontFamily", "var(--font-sans, system-ui, sans-serif)"),
    property("fontWeight", "500"),
    property("border", "none"),
    property("outline", "none"),
    property("cursor", "pointer"),
    property("transition", "all 150ms ease"),
    property("whiteSpace", "nowrap"),
    property("userSelect", "none"),
  ],
  variants: {
    "primary-sm": [
      data("size", "sm"),
      data("variant", "primary"),
      paddingX("spacing-2"),
      paddingY("spacing-1"),
      property("fontSize", "0.875rem"),
      rounded("md"),
      gap("spacing-2"),
      bg("color-primary"),
      text("color-primary-foreground"),
    ],
    "primary-md": [
      data("size", "md"),
      data("variant", "primary"),
      paddingX("spacing-4"),
      paddingY("spacing-2"),
      property("fontSize", "1rem"),
      rounded("md"),
      gap("spacing-2"),
      bg("color-primary"),
      text("color-primary-foreground"),
    ],
    "primary-lg": [
      data("size", "lg"),
      data("variant", "primary"),
      paddingX("spacing-6"),
      paddingY("spacing-3"),
      property("fontSize", "1.125rem"),
      rounded("md"),
      gap("spacing-3"),
      bg("color-primary"),
      text("color-primary-foreground"),
    ],
    "secondary-sm": [
      data("size", "sm"),
      data("variant", "secondary"),
      paddingX("spacing-2"),
      paddingY("spacing-1"),
      property("fontSize", "0.875rem"),
      rounded("md"),
      gap("spacing-2"),
      bg("color-secondary"),
      text("color-secondary-foreground"),
    ],
    "secondary-md": [
      data("size", "md"),
      data("variant", "secondary"),
      paddingX("spacing-4"),
      paddingY("spacing-2"),
      property("fontSize", "1rem"),
      rounded("md"),
      gap("spacing-2"),
      bg("color-secondary"),
      text("color-secondary-foreground"),
    ],
    "secondary-lg": [
      data("size", "lg"),
      data("variant", "secondary"),
      paddingX("spacing-6"),
      paddingY("spacing-3"),
      property("fontSize", "1.125rem"),
      rounded("md"),
      gap("spacing-3"),
      bg("color-secondary"),
      text("color-secondary-foreground"),
    ],
    "outline-sm": [
      data("size", "sm"),
      data("variant", "outline"),
      paddingX("spacing-2"),
      paddingY("spacing-1"),
      property("fontSize", "0.875rem"),
      rounded("md"),
      gap("spacing-2"),
      property("backgroundColor", "transparent"),
      property("border", "1px solid var(--color-border)"),
      text("color-text"),
    ],
    "outline-md": [
      data("size", "md"),
      data("variant", "outline"),
      paddingX("spacing-4"),
      paddingY("spacing-2"),
      property("fontSize", "1rem"),
      rounded("md"),
      gap("spacing-2"),
      property("backgroundColor", "transparent"),
      property("border", "1px solid var(--color-border)"),
      text("color-text"),
    ],
    "outline-lg": [
      data("size", "lg"),
      data("variant", "outline"),
      paddingX("spacing-6"),
      paddingY("spacing-3"),
      property("fontSize", "1.125rem"),
      rounded("md"),
      gap("spacing-3"),
      property("backgroundColor", "transparent"),
      property("border", "1px solid var(--color-border)"),
      text("color-text"),
    ],
    "ghost-sm": [
      data("size", "sm"),
      data("variant", "ghost"),
      paddingX("spacing-2"),
      paddingY("spacing-1"),
      property("fontSize", "0.875rem"),
      rounded("md"),
      gap("spacing-2"),
      property("backgroundColor", "transparent"),
      text("color-text"),
    ],
    "ghost-md": [
      data("size", "md"),
      data("variant", "ghost"),
      paddingX("spacing-4"),
      paddingY("spacing-2"),
      property("fontSize", "1rem"),
      rounded("md"),
      gap("spacing-2"),
      property("backgroundColor", "transparent"),
      text("color-text"),
    ],
    "ghost-lg": [
      data("size", "lg"),
      data("variant", "ghost"),
      paddingX("spacing-6"),
      paddingY("spacing-3"),
      property("fontSize", "1.125rem"),
      rounded("md"),
      gap("spacing-3"),
      property("backgroundColor", "transparent"),
      text("color-text"),
    ],
  },
});
