export { default as Dialog } from "./Dialog.vue";
export { default as DialogTrigger } from "./DialogTrigger.vue";
export { default as DialogContent } from "./DialogContent.vue";
export { default as DialogTitle } from "./DialogTitle.vue";
export { default as DialogDescription } from "./DialogDescription.vue";
export { default as DialogFooter } from "./DialogFooter.vue";
export { default as DialogClose } from "./DialogClose.vue";
export type { DialogProps } from "./Dialog.vue";
export type { DialogContentProps } from "./DialogContent.vue";
export type { DialogButtonProps } from "./context";
