import { defineRecipe, token as t } from "@defied-labs/prism-style-engine";

const control = (height: string, padding: string, fontSize: string, radius: string) => ({
  "slot:trigger": {
    minHeight: t(height as "control.md"),
    paddingInline: t(padding as "space.3"),
    fontSize: t(fontSize as "text.sm"),
    borderRadius: t(radius as "radius.md"),
  },
});

export default defineRecipe({
  name: "select",
  base: {
    position: "relative",
    display: "flex",
    flexDirection: "column",
    gap: t("space.1-5"),
    fontFamily: t("font.sans"),
    color: t("color.fg"),
  },
  slots: {
    trigger: {
      boxSizing: "border-box",
      width: "100%",
      display: "flex",
      alignItems: "center",
      justifyContent: "space-between",
      gap: t("space.2"),
      color: t("color.fg"),
      background: t("color.bg"),
      fontFamily: "inherit",
      lineHeight: t("leading.normal"),
      textAlign: "start",
      cursor: "pointer",
      borderWidth: "1px",
      borderStyle: "solid",
      borderColor: t("color.border-strong"),
      transition: `border-color ${t("duration.fast")} ${t("easing.standard")}`,
      _hover: { borderColor: t("color.fg") },
      _focusVisible: {
        outline: `${t("focus.ring-width")} solid ${t("color.ring")}`,
        outlineOffset: "0",
      },
      _invalid: { borderColor: t("color.danger-solid") },
      _disabled: { opacity: t("opacity.disabled"), cursor: "not-allowed" },
      "part:icon": { flexShrink: "0", color: t("color.muted-fg"), fontSize: t("text.xs") },
    },
    value: {
      overflow: "hidden",
      textOverflow: "ellipsis",
      whiteSpace: "nowrap",
      "part:placeholder": { color: t("color.muted-fg") },
    },
    listbox: {
      position: "absolute",
      zIndex: t("z.dropdown"),
      top: "100%",
      left: "0",
      right: "0",
      marginTop: t("space.1"),
      boxSizing: "border-box",
      padding: t("space.1"),
      maxHeight: "16rem",
      overflowY: "auto",
      borderRadius: t("radius.md"),
      borderWidth: "1px",
      borderStyle: "solid",
      borderColor: t("color.border"),
      background: t("color.bg"),
      boxShadow: t("shadow.lg"),
      // Unrolls down from the trigger; rolls back up on close
      transformOrigin: "top",
      animation: `prism-roll-in ${t("duration.normal")} ${t("easing.emphasized")}`,
      _closed: {
        pointerEvents: "none",
        animation: `prism-roll-out ${t("duration.fast")} ${t("easing.exit")} forwards`,
      },
    },
    option: {
      display: "flex",
      alignItems: "center",
      paddingBlock: t("space.1-5"),
      paddingInline: t("space.2"),
      borderRadius: t("radius.sm"),
      fontSize: t("text.sm"),
      cursor: "pointer",
      userSelect: "none",
      _highlighted: { background: t("color.muted") },
      _selected: { fontWeight: t("weight.semibold") },
      _ariaDisabled: { opacity: t("opacity.disabled"), cursor: "not-allowed" },
    },
    group: {},
    label: {
      paddingBlock: t("space.1-5"),
      paddingInline: t("space.2"),
      color: t("color.muted-fg"),
      fontSize: t("text.xs"),
      fontWeight: t("weight.semibold"),
    },
    separator: {
      height: "1px",
      marginBlock: t("space.1"),
      background: t("color.border"),
    },
  },
  variants: {
    size: {
      sm: control("control.sm", "space.2", "text.sm", "radius.md"),
      md: control("control.md", "space.3", "text.sm", "radius.md"),
      lg: control("control.lg", "space.4", "text.md", "radius.lg"),
    },
  },
  defaultVariants: { size: "md" },
});
